function widget = defineCallbacks(widget)
%defineCallbacks - List of callback declarations for Voxeloc.
%   defineCallbacks(widget) - takes blank widget structure and returns it
%   with updated callbacks.
%
%   Created by J.P.Monney - H.N.L (UNIGE)
%   Last Update: 15/02/2023


% ---------------------- Electrode Parameter Panel ---------------------- %

widget.params.spinner_NumElectrodes.ValueChangedFcn                 = ...
    {@numElectrodeChanged,widget};
widget.params.dropdown_ElectrodeSelector.ValueChangedFcn            = ...
    {@electrodeSelectionChanged,widget};
widget.params.radiogroup1.SelectionChangedFcn                       = ...
    {@hemisphereChanged,widget};
widget.params.field_ElectrodeName.ValueChangedFcn                   = ...
    {@electrodeNameChanged,widget};
widget.params.field_NumContacts.ValueChangedFcn                     = ...
    {@numContactsChanged,widget};
widget.params.field_ContactDistance.ValueChangedFcn                 = ...
    {@contactDistChanged, widget};
widget.params.field_XDeepest.ValueChangedFcn                        = ...
    {@deepCoordsChanged, widget};
widget.params.field_YDeepest.ValueChangedFcn                        = ...
    {@deepCoordsChanged, widget};
widget.params.field_ZDeepest.ValueChangedFcn                        = ...
    {@deepCoordsChanged, widget};
widget.params.button_PickDeepest.ButtonPushedFcn                    = ...
    {@pickButtonPush, widget};
widget.params.field_XSecond.ValueChangedFcn                         = ...
    {@secondCoordsChanged, widget};
widget.params.field_YSecond.ValueChangedFcn                         = ...
    {@secondCoordsChanged, widget};
widget.params.field_ZSecond.ValueChangedFcn                         = ...
    {@secondCoordsChanged, widget};
widget.params.button_PickSecond.ButtonPushedFcn                     = ...
    {@pickButtonPush, widget};
widget.params.button_estimate.ButtonPushedFcn                       = ...
    {@estimateButtonPush, widget};


% ------------------- Slice viewer Glassbrain callbacks ----------------- %

%%% TABS PANEL
widget.viewer.panel_CentralTabsMRI.SelectionChangedFcn              = ...
    {@viewerChanged, widget};

%%% CT TAB
widget.viewer.CT.button_selectNifti.ButtonPushedFcn                 = ...
    {@selectFile, widget};
widget.viewer.CT.field_Xvalue.ValueChangedFcn                       = ...
    {@fieldValueChanged, widget};
widget.viewer.CT.field_Yvalue.ValueChangedFcn                       = ...
    {@fieldValueChanged, widget};
widget.viewer.CT.field_Zvalue.ValueChangedFcn                       = ...
    {@fieldValueChanged, widget};
widget.viewer.CT.slider_X.ValueChangingFcn                          = ...
    {@sliderValueChanging, widget};
widget.viewer.CT.slider_Y.ValueChangingFcn                          = ...
    {@sliderValueChanging, widget};
widget.viewer.CT.slider_Z.ValueChangingFcn                          = ...
    {@sliderValueChanging, widget};
widget.viewer.CT.slider_X.ValueChangedFcn                           = ...
    {@sliderValueChanging, widget};
widget.viewer.CT.slider_Y.ValueChangedFcn                           = ...
    {@sliderValueChanging, widget};
widget.viewer.CT.slider_Z.ValueChangedFcn                           = ...
    {@sliderValueChanging, widget};
widget.viewer.CT.button_smallerX.ButtonPushedFcn                    = ...
    {@smallerButtonPush, widget};
widget.viewer.CT.button_smallerY.ButtonPushedFcn                    = ...
    {@smallerButtonPush, widget};
widget.viewer.CT.button_smallerZ.ButtonPushedFcn                    = ...
    {@smallerButtonPush, widget};
widget.viewer.CT.button_greaterX.ButtonPushedFcn                    = ...
    {@greaterButtonPush, widget};
widget.viewer.CT.button_greaterY.ButtonPushedFcn                    = ...
    {@greaterButtonPush, widget};
widget.viewer.CT.button_greaterZ.ButtonPushedFcn                    = ...
    {@greaterButtonPush, widget};
widget.viewer.CT.slider_contacts.ValueChangedFcn                    = ...
    {@contactSliderValueChanging,widget};
widget.viewer.CT.button_correctContacts.ButtonPushedFcn             = ...
    {@contactCorrect, widget};
widget.viewer.CT.button_resetView.ButtonPushedFcn                   = ...
    {@resetView, widget};
widget.viewer.CT.button_load.ButtonPushedFcn                        = ...
    {@loadVoxelocFile, widget, 0};

%%% T1 TAB
widget.viewer.T1.button_selectNifti.ButtonPushedFcn                 = ...
    {@selectFile, widget};
widget.viewer.T1.field_Xvalue.ValueChangedFcn                       = ...
    {@fieldValueChanged, widget};
widget.viewer.T1.field_Yvalue.ValueChangedFcn                       = ...
    {@fieldValueChanged, widget};
widget.viewer.T1.field_Zvalue.ValueChangedFcn                       = ...
    {@fieldValueChanged, widget};
widget.viewer.T1.slider_X.ValueChangingFcn                          = ...
    {@sliderValueChanging, widget};
widget.viewer.T1.slider_Y.ValueChangingFcn                          = ...
    {@sliderValueChanging, widget};
widget.viewer.T1.slider_Z.ValueChangingFcn                          = ...
    {@sliderValueChanging, widget};
widget.viewer.T1.slider_X.ValueChangedFcn                           = ...
    {@sliderValueChanging, widget};
widget.viewer.T1.slider_Y.ValueChangedFcn                           = ...
    {@sliderValueChanging, widget};
widget.viewer.T1.slider_Z.ValueChangedFcn                           = ...
    {@sliderValueChanging, widget};
widget.viewer.T1.button_smallerX.ButtonPushedFcn                    = ...
    {@smallerButtonPush, widget};
widget.viewer.T1.button_smallerY.ButtonPushedFcn                    = ...
    {@smallerButtonPush, widget};
widget.viewer.T1.button_smallerZ.ButtonPushedFcn                    = ...
    {@smallerButtonPush, widget};
widget.viewer.T1.button_greaterX.ButtonPushedFcn                    = ...
    {@greaterButtonPush, widget};
widget.viewer.T1.button_greaterY.ButtonPushedFcn                    = ...
    {@greaterButtonPush, widget};
widget.viewer.T1.button_greaterZ.ButtonPushedFcn                    = ...
    {@greaterButtonPush, widget};
widget.viewer.T1.slider_contacts.ValueChangedFcn                    = ...
    {@contactSliderValueChanging,widget};

%%% Oblique TAB
widget.viewer.oblique.button_niftiCT.ButtonPushedFcn                = ...
    {@selectFile, widget};
widget.viewer.oblique.button_niftiT1.ButtonPushedFcn                = ...
    {@selectFile, widget};
widget.viewer.oblique.button_niftiParc.ButtonPushedFcn              = ...
    {@selectFile, widget};
widget.viewer.oblique.button_reslice.ButtonPushedFcn                = ...
    {@resliceOblique, widget};
widget.viewer.oblique.checkbox_segCT.ValueChangedFcn                = ...
    {@overlaySeg, widget};
widget.viewer.oblique.checkbox_segT1.ValueChangedFcn                = ...
    {@overlaySeg, widget};
widget.viewer.oblique.slider_opacity.ValueChangingFcn               = ...
    {@opacityValueChanged,widget};
widget.viewer.oblique.slider_opacity.ValueChangedFcn                = ...
    {@opacityValueChanged,widget};
widget.viewer.oblique.button_applyOpacity.ButtonPushedFcn           = ...
    {@applyOpacity, widget};
widget.viewer.oblique.button_exportPDF.ButtonPushedFcn              = ...
    {@exportPDF, widget};

%%% Project TAB
% widget.viewer.projectParams.button_ctFile.ButtonPushedFcn           = ...
%     {@selectFile, widget};
% widget.viewer.projectParams.button_t1File.ButtonPushedFcn           = ...
%     {@selectFile, widget};
% widget.viewer.projectParams.button_parcFile.ButtonPushedFcn         = ...
%     {@selectFile, widget};
% widget.viewer.projectParams.button_patientDir.ButtonPushedFcn       = ...
%     {@patientIDchange, widget};
% widget.viewer.projectParams.field_patientID.ValueChangingFcn        = ...
%     {@patientIDchange, widget};
% widget.viewer.projectParams.field_patientID.ValueChangedFcn         = ...
%     {@patientIDchange, widget};
% widget.viewer.projectParams.field_userID.ValueChangingFcn           = ...
%     {@userIDchange, widget};
% widget.viewer.projectParams.field_userID.ValueChangedFcn            = ...
%     {@userIDchange, widget};
% widget.viewer.projectParams.button_instLogo.ButtonPushedFcn         = ...
%     {@instLogoLoad, widget};
% widget.viewer.projectParams.button_forceSave.ButtonPushedFcn        = ...
%     {@forceSave, widget};


% ------------------------- Tree Nodes callbacks ------------------------ %
widget.tree_Summary.SelectionChangedFcn                             = ...
    {@treeSelectionChange, widget};
widget.tree_buttonUp.ButtonPushedFcn                                = ...
    {@reorderElecs, widget};
widget.tree_buttonDown.ButtonPushedFcn                              = ...
    {@reorderElecs, widget};
widget.tree_buttonColor.ButtonPushedFcn                             = ...
    {@changeElecColor, widget};

% ------------------------- Done Button callbacks ----------------------- %
widget.params.button_done.ButtonPushedFcn                           = ...
    {@donePushed,widget,widget.fig,widget.fig.Position};



end