function electrodeFigure(widget,currElec,outpath)
    scaleFactor = 0.75;
    nContacts = widget.fig.UserData.(currElec).numContacts;
    
    fig = uifigure('Position',[300 300 (10+(400*scaleFactor)+((nContacts-1)*85*scaleFactor)+(135*scaleFactor)+300) (200*scaleFactor)+320],...
        'Color',[1 1 1],'HandleVisibility','on','Visible','off');
    
    [~,~,alpha_head] = imread('electrode_head.png');
    buffer_head = uint8(ones([size(alpha_head),3]).*255);
    im_head = buffer_head - (alpha_head.*0.1);
    panel_head = uipanel('Parent',fig,'Units','pixels','BackgroundColor',[1 1 1],...
        'Position',round([10 ...
        0 ...
        (400*scaleFactor)+((nContacts-1)*85*scaleFactor)+(135*scaleFactor) ...
        (200*scaleFactor)-1]),...
        'BorderType','none');
    disp_head = uiimage('ImageSource',im_head,'Parent',panel_head,...
        'Position',round([0 0 400*scaleFactor 200*scaleFactor]),'ScaleMethod','fill');
    
    [~,~,alpha_contact] = imread('electrode_contact.png');
    buffer_contact = uint8(ones([size(alpha_contact),3]).*255);
    im_contact = buffer_contact - (alpha_contact.*0.5);
    
    for i = 1:(nContacts-1)
        disp_contact(i) = uiimage('ImageSource',im_contact,'Parent',panel_head,...
            'Position',round([400*scaleFactor+((i-1)*85*scaleFactor) ...
            0 ...
            (85*scaleFactor) ...
            (200*scaleFactor)]),...
            'ScaleMethod','fill');
        color_contact(i) = uipanel('Parent',panel_head,'Position',...
            round([400*scaleFactor+((i)*85*scaleFactor)-25*scaleFactor,...
            (200*scaleFactor/2)-(24*scaleFactor/2),...
            24*scaleFactor,...
            24*scaleFactor]),'BackgroundColor',widget.fig.UserData.(currElec).oblique.contacts.regColor(nContacts+1-i,:));
    end
    
    [~,~,alpha_end] = imread('electrode_end.png');
    buffer_end = uint8(ones([size(alpha_end),3]).*255);
    im_end = buffer_end - (alpha_end.*0.5);
    disp_end = uiimage('ImageSource',im_end,'Parent',panel_head,...
        'Position',round([(400*scaleFactor)+((nContacts-1)*85*scaleFactor)...
        0 ...
        135*scaleFactor ...
        200*scaleFactor]),...
        'ScaleMethod','fill');
    i = i+1;
    color_contact(i) = uipanel('Parent',panel_head,'Position',...
            round([400*scaleFactor+((i)*85*scaleFactor)-25*scaleFactor,...
            (200*scaleFactor/2)-(24*scaleFactor/2),...
            24*scaleFactor,...
            24*scaleFactor]),'BackgroundColor',widget.fig.UserData.(currElec).oblique.contacts.regColor(nContacts+1-i,:));
    
    panel_labels = uipanel('Parent',fig,...
        'Position',round([panel_head.Position(1)+disp_head.Position(1)+disp_head.Position(3)+1 ...
        (disp_head.Position(2)+disp_head.Position(4)/2)+20 ...
        fig.Position(3) ... %(fig.Position(4)-panel_head.Position(1)+disp_head.Position(1)+disp_head.Position(3)+1) ...
        fig.Position(4)]),'BorderType','none','BackgroundColor',[1 1 1]);
    
    for i = 1:nContacts
        label_contact(i) = annotation(panel_labels,'textbox','Units','pixels',...
            'String',[num2str(nContacts-i+1) ': ' strrep(widget.fig.UserData.(currElec).oblique.contacts.regName{nContacts+1-i},'-',' ')],...
            'Rotation',45,... %'Position',[85*scaleFactor+((i-1)*85*scaleFactor) 10 550 23],...
            'VerticalAlignment','middle','LineStyle','none','FontSize',26,'FontWeight','bold');
        label_contact(i).Position(1) = 85*scaleFactor+((i-1)*85*scaleFactor);
        label_contact(i).Position(2) = 10;
    end
    diagName = [outpath filesep 'electrodeDiag.png'];
    exportapp(fig,diagName);
    close(fig);

end